export const GETDATA = 'GETDATA'
export const GETLIST = 'GETLIST'
export const GETNEARBY = 'GETNEARBY'
export const CHANGE = 'CHANGE'
export const CHANGES = 'CHANGES'
export const SHOPCAR = 'SHOPCAR'
